### ISSUE TITLE
Detects Unity as gnome

### ISSUE THREAD

**Issue by mdeguzis** [alexeevdv/dename#1]
Using your script:

```
mike@mike-test2:~$ ./desk.sh  -n
GNOME
```

**Comment by alexeevdv** [comment]
fixed, thank you :)

**Comment by mdeguzis** [comment]
awesome , ill try this out. This will help me with my retro gaming project. When running as sudo, I could not find a way (after numerous potential solutions) to get the XDG_CURRENT_DESKTOP var while running in su/sudo/elevated status. I'll report back on how I make out.

**Comment by mdeguzis** [comment]
PERFECT. works on initial try. Should work in my function then. I'll be sure to add your name to my Authors list as a thank you if everything goes well. If you are curious, this applies to my RetroRig-ES project, a fork for my RetroRig project that uses emulation station.

Take care

-PK

**Comment by alexeevdv** [comment]
Glad to hear that this script helps somebody :)
